In [4]:
import os
import pandas as pd
from pathlib import Path

In [5]:
FOLDER = Path("../grades/combined")

# SSR

In [6]:
THRESHOLD = 0.8

In [7]:
rca = FOLDER / "rca_rubric_score.csv"
remediation = FOLDER / "remediation_rubric_score.csv"

In [8]:
df_rca = pd.read_csv(rca)
df_remediation = pd.read_csv(remediation)

In [17]:
df_rca[df_rca["overall_score"] > THRESHOLD]["scenario"].value_counts()

scenario
real-pod-cartservice-cpu-all-one-hour                       13
real-pod-checkoutservice-cpu-all-one-hour                    9
real-pod-recommendationservice-cpu-all-one-hour              9
real-node-cpu-worker-2-one-hour                              9
teastore-pod-registry-capacity-loss-one-hour                 8
teastore-pod-recommender-cpu-all-one-hour                    8
real-pod-paymentservice-capacity-loss-one-hour               7
real-pod-checkoutservice-capacity-loss-one-hour              4
real-node-delay-worker-5-one-hour                            4
real-pod-productcatalogservice-cpu-all-one-hour              4
teastore-node-delay-worker-2-one-hour                        4
teastore-pod-persistence-capacity-loss-one-hour              3
teastore-pod-persistence-cpu-all-one-hour                    3
teastore-pod-auth-cpu-all-one-hour                           3
real-node-delay-worker-3-one-hour                            3
real-node-loss-worker-3-one-hour                             3
real-pod-productcatalogservice-cpu-headroom-all-one-hour     2
real-pod-currencyservice-memory-all-one-hour                 2
real-pod-adservice-memory-all-one-hour                       2
real-pod-paymentservice-cpu-all-one-hour                     2
teastore-pod-image-cpu-all-one-hour                          2
real-node-loss-worker-2-one-hour                             2
real-node-delay-worker-2-one-hour                            1
teastore-pod-registry-cpu-all-one-hour                       1
teastore-pod-webui-cpu-headroom-all-one-hour                 1
Name: count, dtype: int64

In [18]:
df_remediation[df_remediation["overall_score"] > THRESHOLD]["scenario"].value_counts()

scenario
real-node-delay-worker-5-one-hour                  4
real-pod-recommendationservice-cpu-all-one-hour    3
real-pod-currencyservice-memory-all-one-hour       3
real-node-delay-worker-3-one-hour                  2
real-node-loss-worker-2-one-hour                   2
teastore-node-delay-worker-2-one-hour              2
real-node-delay-worker-2-one-hour                  1
real-node-loss-worker-3-one-hour                   1
real-pod-checkoutservice-cpu-all-one-hour          1
real-pod-adservice-memory-all-one-hour             1
teastore-pod-image-cpu-all-one-hour                1
Name: count, dtype: int64

In [13]:
25/43

0.5813953488372093

In [14]:
11/43

0.2558139534883721

In [15]:
df_rca

,run,scenario,job_id,workflow_id,status,alignment,root_cause_correctness_class,root_cause_correctness,causal_reasoning_quality_class,causal_reasoning_quality,evidence_grounding_class,evidence_grounding,localization_accuracy_class,localization_accuracy,diagnostic_completeness_class,diagnostic_completeness,overall_score
0,20260902-122717-01-node-delay-worker-3-agents-...,real-node-delay-worker-3-one-hour,89d9c521-5041-4e3c-9449-84a2fddb656d,d7c28bdb-c977-4741-9b51-668ad5c79ab0,succeeded,not_aligned,MOSTLY_INCORRECT,0.25,PLAUSIBLE,0.50,PARTIALLY_GROUNDED,0.50,WRONG,0.00,INCOMPLETE,0.00,0.3000
1,20260902-122717-01-node-delay-worker-3-agents-...,real-node-delay-worker-3-one-hour,5199f9e8-a8c2-4f87-b3a1-7ba561cfe32a,f801cfc5-5317-4e91-b3bf-920a82d39575,succeeded,aligned,CORRECT,1.00,COMPELLING,1.00,FULLY_GROUNDED,1.00,PRECISE,1.00,COMPLETE,1.00,1.0000
2,20260902-122717-01-node-delay-worker-3-agents-...,real-node-delay-worker-3-one-hour,bb117773-c136-4c05-89aa-ff67724da3d8,14a13c82-be94-4405-818f-54b09132acd0,succeeded,aligned,CORRECT,1.00,STRONG,0.75,FULLY_GROUNDED,1.00,PRECISE,1.00,COMPLETE,1.00,0.9375
3,20260902-122717-01-node-delay-worker-3-agents-...,real-node-delay-worker-3-one-hour,fc564a79-8e06-4340-a3b9-c0a121018fd0,15458581-7f4a-44f3-b32f-ee006135af57,succeeded,not_aligned,INCORRECT,0.00,PLAUSIBLE,0.50,PARTIALLY_GROUNDED,0.50,WRONG,0.00,INCOMPLETE,0.00,0.2250
4,20260902-122717-01-node-delay-worker-3-agents-...,real-node-delay-worker-3-one-hour,8f379dc3-6471-4dd1-b99c-7b7b0e6190f1,adc5fa9b-a6f9-46fe-b8c7-84f3aeb5d6eb,succeeded,aligned,CORRECT,1.00,STRONG,0.75,FULLY_GROUNDED,1.00,PRECISE,1.00,COMPLETE,1.00,0.9375
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321,20260910-164433-21-pod-webui-cpu-headroom-all-...,teastore-pod-webui-cpu-headroom-all-one-hour,7e62b739-ccf9-495f-aaf2-88488e84f568,a5384884-be0c-43c8-a10c-756b6f2309d7,succeeded,not_aligned,PARTIALLY_CORRECT,0.50,STRONG,0.75,WELL_GROUNDED,0.75,PRECISE,1.00,MOSTLY_COMPLETE,0.75,0.7125
322,20260910-164433-21-pod-webui-cpu-headroom-all-...,teastore-pod-webui-cpu-headroom-all-one-hour,265aca49-32cd-46e1-8bae-3298b8277ae5,d3d2d61a-0afc-47e3-a0c3-819008ca3315,succeeded,aligned,MOSTLY_CORRECT,0.75,COMPELLING,1.00,FULLY_GROUNDED,1.00,PRECISE,1.00,COMPLETE,1.00,0.9250
323,20260910-164433-21-pod-webui-cpu-headroom-all-...,teastore-pod-webui-cpu-headroom-all-one-hour,f95e96de-e5c6-4621-948e-24ef8488de4e,da6e7be2-9b18-446e-951b-4b619942b244,succeeded,not_aligned,MOSTLY_INCORRECT,0.25,PLAUSIBLE,0.50,WEAKLY_GROUNDED,0.25,PRECISE,1.00,PARTIAL,0.50,0.4500
324,20260910-164433-21-pod-webui-cpu-headroom-all-...,teastore-pod-webui-cpu-headroom-all-one-hour,72ddf908-d7e8-426e-abd2-1af0c5fd056d,665adb83-5616-4144-8bb5-928feb2c85b1,succeeded,not_aligned,MOSTLY_INCORRECT,0.25,PLAUSIBLE,0.50,PARTIALLY_GROUNDED,0.50,MOSTLY_PRECISE,0.75,PARTIAL,0.50,0.4625
325,20260910-164433-21-pod-webui-cpu-headroom-all-...,teastore-pod-webui-cpu-headroom-all-one-hour,1741325d-545f-443c-90e7-8bab0ba2e9c1,5732b822-ff73-49ef-accc-6b51b98c23a2,running,not_evaluable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df_remediation

,run,scenario,job_id,workflow_id,status,alignment,remediation_correctness_class,remediation_correctness,technical_feasibility_class,technical_feasibility,risk_and_safety_class,risk_and_safety,evidence_alignment_class,evidence_alignment,remediation_completeness_class,remediation_completeness,rubric_score,penalty_total,overall_score
0,20260902-122717-01-node-delay-worker-3-agents-...,real-node-delay-worker-3-one-hour,21e7e1e1-162b-497b-b0c9-7af403c73bc8,d7c28bdb-c977-4741-9b51-668ad5c79ab0,needs_review,not_evaluable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20260902-122717-01-node-delay-worker-3-agents-...,real-node-delay-worker-3-one-hour,ae6cf7aa-dda7-455f-bf23-9c2fa10b2b44,f801cfc5-5317-4e91-b3bf-920a82d39575,succeeded,aligned,CORRECT,1.00,FEASIBLE,1.0,SAFE,1.00,FULLY_ALIGNED,1.00,COMPLETE,1.00,1.0000,0.00,1.0000
2,20260902-122717-01-node-delay-worker-3-agents-...,real-node-delay-worker-3-one-hour,5e411432-f383-4da1-b914-85e5897b93af,15458581-7f4a-44f3-b32f-ee006135af57,succeeded,not_aligned,INCORRECT,0.00,FEASIBLE,1.0,RISKY,0.25,UNALIGNED,0.00,INCOMPLETE,0.00,0.2500,0.25,0.0000
3,20260902-122717-01-node-delay-worker-3-agents-...,real-node-delay-worker-3-one-hour,d5cdfd33-a935-4e25-8129-ab3d48276893,adc5fa9b-a6f9-46fe-b8c7-84f3aeb5d6eb,succeeded,aligned,MOSTLY_CORRECT,0.75,FEASIBLE,1.0,SAFE,1.00,FULLY_ALIGNED,1.00,MOSTLY_COMPLETE,0.75,0.8875,0.00,0.8875
4,20260902-122717-01-node-delay-worker-3-agents-...,real-node-delay-worker-3-one-hour,03d2477a-9122-4ea0-82f2-df8cbf774d09,35f896c5-c597-444f-9aa5-0b4a10b99702,succeeded,not_aligned,INCORRECT,0.00,FEASIBLE,1.0,LOW_RISK,0.75,UNALIGNED,0.00,INCOMPLETE,0.00,0.3500,0.00,0.3500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,20260910-164433-21-pod-webui-cpu-headroom-all-...,teastore-pod-webui-cpu-headroom-all-one-hour,188aeee5-5f60-475a-96ae-0d5526170fcb,35aaf9fe-878c-41f3-8fd9-b05a9dbe2443,succeeded,not_aligned,MOSTLY_INCORRECT,0.25,FEASIBLE,1.0,LOW_RISK,0.75,WEAKLY_ALIGNED,0.25,INCOMPLETE,0.00,0.4625,0.00,0.4625
255,20260910-164433-21-pod-webui-cpu-headroom-all-...,teastore-pod-webui-cpu-headroom-all-one-hour,3390d046-290d-4cad-b949-8b912265a1fc,a5384884-be0c-43c8-a10c-756b6f2309d7,succeeded,not_aligned,INCORRECT,0.00,FEASIBLE,1.0,HIGH_RISK,0.00,UNALIGNED,0.00,INCOMPLETE,0.00,0.2000,0.00,0.2000
256,20260910-164433-21-pod-webui-cpu-headroom-all-...,teastore-pod-webui-cpu-headroom-all-one-hour,c9db6b70-1ce3-45a2-bfa6-6e1673f68974,d3d2d61a-0afc-47e3-a0c3-819008ca3315,succeeded,not_aligned,INCORRECT,0.00,FEASIBLE,1.0,RISKY,0.25,UNALIGNED,0.00,INCOMPLETE,0.00,0.2500,0.00,0.2500
257,20260910-164433-21-pod-webui-cpu-headroom-all-...,teastore-pod-webui-cpu-headroom-all-one-hour,9c530636-60ff-4ce9-8510-21265b36524a,da6e7be2-9b18-446e-951b-4b619942b244,succeeded,not_aligned,INCORRECT,0.00,FEASIBLE,1.0,HIGH_RISK,0.00,UNALIGNED,0.00,INCOMPLETE,0.00,0.2000,0.00,0.2000
258,20260910-164433-21-pod-webui-cpu-headroom-all-...,teastore-pod-webui-cpu-headroom-all-one-hour,044e02de-1ad3-4e84-af84-f4889cde7afd,665adb83-5616-4144-8bb5-928feb2c85b1,succeeded,not_aligned,INCORRECT,0.00,FEASIBLE,1.0,HIGH_RISK,0.00,UNALIGNED,0.00,INCOMPLETE,0.00,0.2000,0.00,0.2000